apiVersion: batch/v1
kind: CronJob
metadata:
  name: scrape-vacuum-bin
spec:
  schedule: "05 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraper-container
            image: ghcr.io/dbeltman/roborock-bin2mqtt:develop
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: bin2mqtt-secret      
            volumeMounts:
            - name: bin2mqtt-ssh-key
              readOnly: true
              mountPath: "/app/keys/robokey"                  
            # command:
            # - /bin/sh
            # - -c
            # - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: docker-credentials